language: node_js

services:
  - docker

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
    - npm install
    - composer install

jobs:
    include:
        - name: End-to-end (e2e) tests
          script:
            - npm run build
            - npm run e2e:ci
