name: ESLint Report
on:
    workflow_run:
        workflows: ['Linting']
        types: [completed]
jobs:
    on-success:
        runs-on: ubuntu-latest
        steps:
            - name: Download eslint_report.json
              uses: actions/download-artifact@v2
              with:
                  name: eslint_report.json
            - name: Annotate Code Linting Results
              uses: ataylorme/eslint-annotate-action@1.2.0
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  report-json: 'eslint_report.json'
