name: ESLint Report
on:
    workflow_run:
        workflows: ['Linting']
        types: [completed]
jobs:
    eslint-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.workflow_run.head_branch }}
            - name: Download eslint_report.json
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: ${{ github.event.workflow_run.workflow_id }}
                  name: eslint_report.json
            - name: Annotate Code Linting Results
              uses: ataylorme/eslint-annotate-action@1.2.0
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  report-json: 'eslint_report.json'
